### ISSUE TITLE
defs for procedures from 1992 version

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-scma#11]
example for http://anzsoil.org/def/au/scma/14E2
that was included in this vocab but superseded in 2011 version by  
http://anzsoil.org/def/au/scma/14E2a and http://anzsoil.org/def/au/scma/14E2b

Should we have the defs in for these? if so, the full text only appears to be in hardcopy so may have to be typed.....

Rayment, G. E & Higginson, F. R. (Francis Ross), 1943- (1992). Australian laboratory handbook of soil and water chemical methods. Inkata Press, Port Melbourne

https://trove.nla.gov.au/work/34824443
ISBN 0909605688 :Dewey Number 546.22078Libraries Australia ID 9032227

**Comment by dr-shorthair** [comment]
I think we should manage the SCMA definitions one-by-one rather than as-a-set. 
So superseded methods would be in the registry, since there may be old data that used them and we need to be able to access the description of the method. 

This does suggest that there must be a 'status' flag on each one, with pointers to the preferred methods from the retired ones.

**Comment by meganrwong** [comment]
Re 'status' flag - related to #12 
Flagging work of getting defs of 1992 out of the print version. Perhaps one of the soil chem folks has text digitalized somewhere.

**Comment by meganrwong** [comment]
same as #22 - so closing
