### ISSUE TITLE
Fix Notation values so they sort right

### ISSUE THREAD

**Issue by dr-shorthair** [ANZSoilData/def-au-scma#20]
Notations starting 2-9 need a '0' in front so they sort before the 10-19 methods

**Comment by meganrwong** [comment]
Apologies just getting back into green book work. Seems you have beaten me to this @dr-shorthair 

 eg zero is added in front of each fragment from chapters 1 - 9, and you have fixed up the numbers of front and backmatter so they sort better? eg  [9A2.html] to [09A2.html] (https://github.com/ANZSoilData/def-au-scma/blob/main/html/09-P/09A2.html)

If so, thank you. I'll close this and get onto task #21

**Comment by meganrwong** [comment]
Also, to confirm - we decided to leave the skos:notation and URIs as is. We are only adding the zero in front of the notations in the html fragments for sorting?
eg skos:notation "1" , URI http://anzsoil.org/def/au/scma/1 right?


If we prefer zeros added in skos:notation and URIs as well, I can add. It does not seem necessary to me, but you may know otherwise from your experiences Simon

**Comment by meganrwong** [comment]
hmmm. Wait a minute - online we just talked about putting zeros in front of notation and the URIs. 
But did we ever implement the anzsoil URIs when SCMA was up in LDR? I can't recall!
What I wonder is are there many folks out there using http://anzsoil.org/def/au/scma/1 ? The soil data federator? TERN?
Should we put a 0 in front of the 1 here?
I'll just change in the notation now, until I hear back what you think @dr-shorthair

**Comment by dr-shorthair** [comment]
Noone has used it. That isn’t a problem. 

Would definitely be smart to insert the zeroes in the `skos:notation` values at least Those are used for sorting.

**Comment by meganrwong** [comment]
Zeros inserted in skos:notation and URIs. 
Described changes and recalled how to commit to main branch and push - thanks for help there!
